### ISSUE TITLE
No file extensions for python files

### ISSUE THREAD

**Issue by stuaxo** [ldo/python_pixman_examples#1]
Hi,
   It would be good if the python files had .py extensions in case people want to use these in Windows one day.

Cheers
S

**Comment by ldo** [comment]
Trouble is, Windows has at least two different extensions for Python scripts, .py or .pyw, so which should I choose?

Can’t be bothered.

**Comment by stuaxo** [comment]
True ...  .pyw is for ones that don't use the console, .py is usually the sane option.
